#!/usr/bin/env bash
# Configuration lines to enable connection to server without
# typing a password

Host *
    PasswordAuthentication no

Host myserver
    Hostname <54.174.194.149>
    User <ubuntu>
    IdentityFile ~/.ssh/school
